[package]
name = "mavlink-camera-manager"
version = "0.1.0"
description = "Mavlink Camera Manager"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path = "src/main.rs"
name = "mavlink-camera-manager"

[dependencies]
clap = "2"
pnet = "0.25"
regex = "1.3"

## Mavlink
mavlink = { version = "0.8", features = ["default", "emit-extensions"] }

## RTSP server
failure = "0.1"
failure_derive = "0.1"
glib = "0.9"
gstreamer = "0.15"
gstreamer-rtsp-server = "0.15"
