[package]
name = "mavlink-camera-manager"
version = "0.2.2"
description = "Mavlink Camera Manager"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

readme = "README.md"
documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path = "src/main.rs"
name = "mavlink-camera-manager"

[dependencies]
clap = "2"
pnet = "0.25"
regex = "1.3"

## Mavlink
mavlink = { version = "0.8.1", features = ["default", "emit-extensions"] }

## RTSP server
glib = { version = "0.9", optional = true }
gstreamer = { version = "0.15", optional = true }
gstreamer-rtsp-server = { version = "0.15", optional = true }

[features]
gst = ["glib", "gstreamer"]
rtsp = ["gst", "gstreamer-rtsp-server"]
default = []
