[package]
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
description = "Mavlink Camera Manager"
edition = "2018"
license = "MIT"
name = "mavlink-camera-manager"
version = "0.2.4"

documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
readme = "README.md"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main.rs"

[dependencies]
clap = "2"
regex = "1.3"
toml = {version = "0.5.6", features = ["preserve_order"]}

actix-cors = "0.1"
actix-web = "1.0.9"
derivative = "2.1.1"
dirs = "3.0"
notify = "4.0.15"
serde = "^1.0.8"
serde_derive = "^1.0.8"
serde_json = "^1.0.41"

## FINAL
lazy_static = "1.4.0"
quick-xml = {version = "0.21", features = ["serialize"]}
simple-error = "0.2"
v4l = "0.12.0"

## Mavlink
mavlink = {version = "0.8.6", features = ["default", "emit-extensions"]}

## RTSP server
glib = {version = "0.10.2", optional = true}
gstreamer = {version = "0.16.3", optional = true}
gstreamer-rtsp-server = {version = "0.16.3", optional = true}

[dev-dependencies]
rand = "0.8"

[features]
default = ["rtsp"]
gst = ["glib", "gstreamer"]
rtsp = ["gst", "gstreamer-rtsp-server"]
