[package]
name = "ardupilot-camera-manager"
version = "0.1.0"
description = "Ardupilot Camera Manager"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path = "src/main.rs"
name = "ardupilot-camera-manager"

[dependencies]
clap = "2"
pnet = "0.25"
regex = "1.3"

## Mavlink
# wait for 0.6+ version
mavlink = { git = "https://github.com/mavlink/rust-mavlink", branch = "master" }

## RTSP server
failure = "0.1"
failure_derive = "0.1"
glib = "0.9"
gstreamer = "0.15"
gstreamer-rtsp-server = "0.15"
